version: '3.7'
name: 'coditime-api'
services:
    mongo:
        image: mongo:6.0.4
        restart: unless-stopped
        volumes:
            - mongodb_data:/data/db
            - mongodb_config:/data/configdb
        networks:
            - default
        ports:
            - '27018:27017'
    api:
        depends_on:
            - mongo
        restart: unless-stopped
        build:
            context: ./
            dockerfile: Dockerfile
        environment:
            - MONGODB_URI=mongodb://mongo:27017/coditime
        networks:
            - default
        ports:
            - '3000:3000'
networks:
    default:
volumes:
    mongodb_data:
    mongodb_config:
